In [ ]:
#instal below  things
#conda install -c conda-forge tensorflow 
#conda create -n tf tensorflow
#conda activate tf

In [1]:
# Numpy allows us to work with array.
import numpy as np

# Pandas allows us to not only import the datasets but also create the matrix of features(independent) and 
# dependent variable.
import pandas as pd

# TensorFlow has a comprehensive, flexible ecosystem of tools, libraries and community resources that lets researchers 
# push the state-of-the-art in ML and developers easily build and deploy ML powered applications.
import tensorflow as tf

F:\MSIT\Data science\anaconda\lib\site-packages\h5py\__init__.py:72: UserWarning: h5py is running against HDF5 1.10.2 when it was built against 1.10.3, this may cause problems
  '{0}.{1}.{2}'.format(*version.hdf5_built_version_tuple)


In [2]:
dataset = pd.read_csv('Churn_Modelling.csv')
x = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

print(x)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [3]:
print(y)

[1 0 1 ... 1 1 0]


In [4]:
# Importing Package
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

x[:, 2] = le.fit_transform(x[:, 2])

print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [5]:
# Importing Package
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

print(x)
# France = 1 0 0
# Spain = 0 0 1
# Germany = 0 1 0


[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [6]:
# Importing Packaage
from sklearn.model_selection import train_test_split

# Dividing training and test set.
# The best ratio is 80 - 20 for trainging and testing respectively.
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

print(x_train)

[[0.0 1.0 0.0 ... 0 1 124749.08]
 [1.0 0.0 0.0 ... 0 0 41104.82]
 [0.0 1.0 0.0 ... 1 1 45750.21]
 ...
 [1.0 0.0 0.0 ... 1 1 92027.69]
 [1.0 0.0 0.0 ... 1 1 101168.9]
 [0.0 1.0 0.0 ... 1 0 33462.94]]


In [7]:
# Importing Package
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

print(x_train)

[[-0.99850112  1.71490137 -0.57273139 ... -1.55337352  0.97725852
   0.42739449]
 [ 1.00150113 -0.58312392 -0.57273139 ... -1.55337352 -1.02327069
  -1.02548708]
 [-0.99850112  1.71490137 -0.57273139 ...  0.64376017  0.97725852
  -0.94479772]
 ...
 [ 1.00150113 -0.58312392 -0.57273139 ...  0.64376017  0.97725852
  -0.14096853]
 [ 1.00150113 -0.58312392 -0.57273139 ...  0.64376017  0.97725852
   0.01781218]
 [-0.99850112  1.71490137 -0.57273139 ...  0.64376017 -1.02327069
  -1.15822478]]


In [8]:
print(x_test)

[[ 0.98019606 -0.56118125 -0.57812007 ...  0.65543311  0.9426421
  -0.04925965]
 [ 0.98019606 -0.56118125 -0.57812007 ...  0.65543311 -1.06084802
  -0.58254072]
 [ 0.98019606 -0.56118125 -0.57812007 ... -1.52570869  0.9426421
  -0.16313933]
 ...
 [-1.02020406 -0.56118125  1.72974448 ... -1.52570869  0.9426421
   1.07759708]
 [-1.02020406  1.78195548 -0.57812007 ...  0.65543311  0.9426421
   1.14197101]
 [-1.02020406  1.78195548 -0.57812007 ...  0.65543311  0.9426421
  -0.88821212]]


In [9]:
# An instance of the sequential class which intializes as a sequence of layers.
ann = tf.keras.models.Sequential()


In [10]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [11]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [12]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [13]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [14]:
ann.fit(x_train, y_train, batch_size = 32, epochs = 100)

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Epoch 1/100
8000/8000 [==============================] - 1s 90us/sample - loss: 0.5746 - acc: 0.7485
Epoch 2/100
8000/8000 [==============================] - 0s 31us/sample - loss: 0.4699 - acc: 0.7972
Epoch 3/100
8000/8000 [==============================] - 0s 25us/sample - loss: 0.4397 - acc: 0.7983
Epoch 4/100
8000/8000 [==============================] - 0s 30us/sample - loss: 0.4189 - acc: 0.8084
Epoch 5/100
8000/8000 [==============================] - 0s 31us/sample - loss: 0.4044 - acc: 0.8152
Epoch 6/100
8000/8000 [==============================] - 0s 29us/sample - loss: 0.3926 - acc: 0.82670s - loss: 0.4157 - acc: 0.
Epoch 7/100
8000/8000 [==============================] - 0s 28us/sample - loss: 0.3814 - acc: 0.83700s - loss: 0.3858 - acc: 0.83
Epoch 8/100
8000/8000 [==============================] - 0s 26us/sample - loss: 0.3726 - acc: 0.8413
Epoch 9/100
8000/8000 [===================

8000/8000 [==============================] - 0s 27us/sample - loss: 0.3361 - acc: 0.86150s - loss: 0.3612 - acc: 0.8
Epoch 74/100
8000/8000 [==============================] - 0s 25us/sample - loss: 0.3363 - acc: 0.8625
Epoch 75/100
8000/8000 [==============================] - 0s 25us/sample - loss: 0.3359 - acc: 0.8606
Epoch 76/100
8000/8000 [==============================] - 0s 25us/sample - loss: 0.3358 - acc: 0.8618
Epoch 77/100
8000/8000 [==============================] - 0s 25us/sample - loss: 0.3361 - acc: 0.8616
Epoch 78/100
8000/8000 [==============================] - 0s 26us/sample - loss: 0.3358 - acc: 0.8626
Epoch 79/100
8000/8000 [==============================] - 0s 25us/sample - loss: 0.3356 - acc: 0.8611
Epoch 80/100
8000/8000 [==============================] - ETA: 0s - loss: 0.3346 - acc: 0.8640- ETA: 0s - loss: 0.3334 - acc: 0.8 - 0s 25us/sample - loss: 0.3356 - acc: 0.8630
Epoch 81/100
8000/8000 [==============================] - 0s 25us/sample - loss: 0.3357 - acc: 

In [15]:
#extras

In [16]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

[[False]]


In [17]:
# Predicting
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]
